language: cpp

dist: trusty

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
      - gcc-7
      - libx11-dev
      - libxft-dev

install: 
  - export CXX="g++-7" CC="gcc-7"

script:
  - mkdir build-release && cd build-release
  - cmake -DCMAKE_BUILD_TYPE=Release ..
  - make -j2
  - mkdir ../build-test && cd ../build-test
  - cmake -DCMAKE_BUILD_TYPE=Debug .. && cd tests
  - make -j2 && ctest -C Debug -V
